update

diff --git a/.github/workflows/image-build.yml b/.github/workflows/image-build.yml
--- a/.github/workflows/image-build.yml
+++ b/.github/workflows/image-build.yml
@@ -20,7 +20,7 @@ jobs:
         uses: docker/setup-buildx-action@v2
       
       - name: Debug Login
-          run: echo "Attempting login with user ${{ github.actor }}" && docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} || echo "Login failed"
+        run: echo "Attempting login with user ${{ github.actor }}" && docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} || echo "Login failed"
           
       - name: Login to GHCR
         uses: docker/login-action@v2
